### ISSUE TITLE
공이 밖으로 나간다.

### ISSUE THREAD

**Issue by shieldnet** [leesnhyun/OOP_PocketBall#1]
모서리에서 공을 반복적으로 밖으로 보내려고 하면, 공이 밖으로 나갑니다.

![image](https://user-images.githubusercontent.com/9548599/32597544-5fdcdd08-c57a-11e7-9754-cb52e8c3b002.png)

**Comment by tjdgus3537** [comment]
죄송합니다. 아마 제가 짠 로직에 문제가 있을 거 같은데 군인이라 수정을 못해요.
